version: "3"
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8000'
        gitlab_rails['initial_root_password'] = 'adminadmin'
    ports:
      - '8000:8000'
      - '8443:8443'
      - '122:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    restart: always
    hostname: 'jenkins'
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
  jenkins_home:
 
